"use client";

/**
 * Live AI Analytics Report banner — auto-refreshes every 60s with a
 * 2-line market brief generated by AltLLM from Nansen smart-money flows
 * and ELFA trending tickers. Renders above all tabs.
 */

import { useCallback, useEffect, useRef, useState } from "react";
import { altLLMChat, altLLMMessage } from "@/lib/intelligence/altllm";
import { liveBannerPrompt } from "@/lib/intelligence/prompts";
import { nansenTopNetflow } from "@/lib/intelligence/nansen";
import { elfaTrendingTokens } from "@/lib/intelligence/elfa";
import { useStocky } from "./StockyContext";
import { uiStrings } from "@/lib/intelligence/lang";

const REFRESH_MS = 60_000;

interface BannerData {
  bullets: string[];
  generatedAt: number;
  topInflowSymbol?: string;
  topInflowAmount?: number;
  topTrendingSymbol?: string;
  topTrendingChange?: number;
}

function parseBullets(text: string): string[] {
  return text
    .split("\n")
    .map(s => s.trim())
    .filter(s => s.length > 0)
    .map(s => s.replace(/^[-•*]\s*/, ""))
    .filter(s => s.length > 0)
    .slice(0, 2);
}

function ago(ts: number): string {
  const s = Math.max(0, Math.floor((Date.now() - ts) / 1000));
  if (s < 60) return `${s}s`;
  if (s < 3600) return `${Math.floor(s / 60)}m`;
  return `${Math.floor(s / 3600)}h`;
}

export function LiveAnalyticsBanner() {
  const { state, open } = useStocky();
  const t = uiStrings(state.lang);
  const [data, setData] = useState<BannerData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [tick, setTick] = useState(0);
  const inflight = useRef(false);

  const refresh = useCallback(async () => {
    if (inflight.current) return;
    inflight.current = true;
    setLoading(true);
    try {
      const [topInflows, trending] = await Promise.all([
        nansenTopNetflow(["mantle", "ethereum"], 5).catch(() => []),
        elfaTrendingTokens("24h", 5).catch(() => []),
      ]);
      const samples = {
        topInflows: topInflows.map(t => ({ symbol: t.symbol, netFlow24h: t.netFlow24h ?? 0 })),
        trendingTokens: trending.map(t => ({ token: t.token, change_percent: t.change_percent })),
      };
      const resp = await altLLMChat(
        {
          // altllm-basic is non-reasoning → returns content immediately;
          // altllm-standard uses 200+ tokens on reasoning_content and would
          // hit finish_reason="length" with content=null at low max_tokens.
          model: "altllm-basic",
          messages: [
            { role: "system", content: "You write ultra-concise 2-line market briefs. No markdown headings, no preamble." },
            { role: "user", content: liveBannerPrompt(state.lang, samples) },
          ],
          max_tokens: 220,
          temperature: 0.6,
        },
        { timeoutMs: 30_000 },
      );
      const text = altLLMMessage(resp)?.content ?? "";
      const bullets = parseBullets(text);
      setData({
        bullets: bullets.length ? bullets : ["Live data refreshing…", "Loading market context…"],
        generatedAt: Date.now(),
        topInflowSymbol: topInflows[0]?.symbol,
        topInflowAmount: topInflows[0]?.netFlow24h,
        topTrendingSymbol: trending[0]?.token,
        topTrendingChange: trending[0]?.change_percent,
      });
      setError(null);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Live brief failed");
    } finally {
      setLoading(false);
      inflight.current = false;
    }
  }, [state.lang]);

  useEffect(() => {
    refresh();
    const id = setInterval(() => refresh(), REFRESH_MS);
    const tickId = setInterval(() => setTick(x => x + 1), 5_000);
    return () => { clearInterval(id); clearInterval(tickId); };
  }, [refresh]);

  return (
    <div className="rounded-2xl border border-emerald-500/20 bg-gradient-to-r from-emerald-500/[0.06] via-teal-500/[0.04] to-transparent overflow-hidden">
      <div className="px-4 py-2.5">
        <div className="flex items-center gap-2 flex-wrap">
          <div className="flex items-center gap-1.5">
            <span className={`w-2 h-2 rounded-full ${loading ? "bg-amber-300 animate-pulse" : "bg-emerald-400 animate-pulse"}`} />
            <span className="text-[10px] font-bold tracking-[0.18em] text-emerald-300 uppercase">{t.liveBrief}</span>
          </div>
          <span className="text-[9px] text-white/30 tracking-wide hidden sm:inline">Nansen · ELFA · AltLLM</span>
          <div className="ml-auto flex items-center gap-2">
            {data && (
              <span className="text-[10px] text-white/40 tabular-nums" title={new Date(data.generatedAt).toUTCString()}>
                {ago(data.generatedAt)} <span className="text-white/30">ago</span>
                {/* tick keeps the "ago" string fresh */}
                <span className="hidden">{tick}</span>
              </span>
            )}
            <button
              onClick={() => open("floating")}
              className="text-[10px] font-medium px-2 py-0.5 rounded-full bg-emerald-500/15 hover:bg-emerald-500/25 border border-emerald-500/30 text-emerald-200 transition-colors"
            >
              Ask Stocky →
            </button>
          </div>
        </div>
        <div className="mt-1.5 space-y-0.5">
          {error && <div className="text-[11px] text-rose-300/80">{error}</div>}
          {!error && data?.bullets.map((b, i) => (
            <div key={i} className="flex items-start gap-1.5 text-[12px] text-white/85 leading-snug">
              <span className="text-emerald-300/70 mt-0.5 shrink-0">›</span>
              <span>{b}</span>
            </div>
          ))}
          {!error && !data && (
            <div className="text-[11px] text-white/40">Loading live brief…</div>
          )}
        </div>
      </div>
    </div>
  );
}
